README.md
리드미 수정 및 develop 브랜치 생성
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> :memo: Docs: README 수정

src/App.tsx, src/components/createButton/TeamRetroCreateButton.tsx, src/pages/TemplateNothingPage.tsx, webpack.config.js, yarn.lock
라우터 추가
<br><br>
작업 중 라우터 문제 발생해서 수정함
webpack.config.js 에 historyApiFallback: true 추가하고,
yarn add react-router-dom 설치함
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> :construction_worker: Chore: 라우터 문제 해결

.eslintrc.json, .prettierrc, package-lock.json, package.json, src/components/common/NavBar.tsx, yarn.lock
- eslint 설치
- eslint airbnb 정책으로 다시 설치
[참고자료](https://leo-xee.github.io/React/react-setup-eslint/)
=> #12 🐛Fix: yarn add eslint-airbnb 다시 설치

.github/CODEOWNERS, yarn.lock
- adfadsf
- adfadsf
- adsfadsf
- 없음 ㅋ
- Close #1
=> #1 CODEOWNERS 설정 추가

yarn.lock
develop 브랜치 관련
<br><br>
<br><br>
희정님이 요청하심
<br><br>
- Close #32
<br><br>
=> #32 develop 브랜치 커밋

src/components/createRetro/CreateButtonBox.tsx, src/components/createRetro/DescriptionBox.tsx, src/components/createRetro/PersonalRetroDescription.tsx, src/components/createRetro/TeamRetroDescription.tsx, src/pages/CreateRetroPage.tsx, src/styles/createRetro/CreateButtonBox.style.ts, src/styles/createRetro/Description.style.ts, src/styles/createRetro/DescriptionBox.style.ts
Retro NothingPage 퍼블리싱 완료
<br><br>
- TeamRetro Create 버튼 생성 완료
- PersonalRetro Create 버튼 생성 완료
- 회고에 대한 설명 첨부 완료
<br><br>
<br><br>
- Close #6 
<br><br>
=> [FE][Feature] RetroList Nothing Page 퍼블리싱

public/index.html, src/components/writeRetro/Message.tsx, src/components/writeRetro/Task.tsx, src/components/writeRetro/TaskMessage.tsx, src/styles/writeRetroStyles/Message.style.ts, src/styles/writeRetroStyles/Task.style.ts, src/styles/writeRetroStyles/TaskMessage.style.ts
- Task 컴포넌트 추
<br><br>
- Task 작성자명 표시
- Task 작성자 프로필 표시
- Task 제목 표시
- 좋아요 아이콘 및 횟수 표시
- 댓글 아이콘 및 횟수 표시
- 시간 아이콘 및 시간 표시
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> :sparkles: Feat: Task 컴포넌트 추가 (#38)

src/components/createRetro/modal/ImageUpload.tsx
imageUpload 컴포넌트 안 쓰는 변수 제거 및 버튼 추가
<br><br>
쓰이지 않는 selectedImage 변수 제거
이미지 제거 버튼 만들기
필요 없는 주석 삭제
<br><br>
<br><br>
- Close #65 
<br><br>
=> [FE][Fix] imageUpload 컴포넌트 수정

src/components/RetroListHaveSth/ContentsList.tsx, src/components/RetroListHaveSth/RetroListSearch.tsx, src/pages/RetroListHaveSthPage.tsx
RetroList 검색 기능 구현
RetroList 검색 기능 구현
<br><br>
- Close #58
<br><br>
=> #58 [Feature] RetroList 검색 기능 구현

.gitignore, webpack.config.js
- 웹팩 빌드 엔트리 파일 오류 수정
- git ignore에 빌드 파일 추가
=> Build: 웹팩 빌드 엔트리 파일 오류 수정 및 gitignore 추가

src/api/@types/@enums.ts, src/api/@types/RetrospectiveTemplates.ts, src/api/@types/Retrospectives.ts, src/api/__mock__/retrospectiveTemplate.ts, src/api/services/RetrospectiveTemplate.ts, src/api/services/Retrospectives.ts, src/components/layout/parts/MainNavBar.tsx, src/components/layout/parts/ProfileNavBar.tsx, src/components/my/EmailBox.tsx, src/components/my/PasswordBox.tsx, src/mocks/handlers.ts, src/pages/MyPage.tsx, src/styles/layout/layout.style.ts, src/styles/my/myPage.style.ts
MSW 및 자잘한 에러수정
<br><br>
- Close #이슈번호
<br><br>
=> #79 [Fix] MSW 및 자잘한 에러수정

package.json, yarn.lock
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18XJFhSllpyXdH2cJrbfdgXnxkYvz8IqMI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=8gWqJwv)
conflict 해결 과정 중 지워진 package.json 오타 수정
<br><br>
package.json에 "," 추가
<br><br>
<br><br>
- Close #84 
<br><br>
=> [FE][Fix] conflict 해결 과정 중 지워진 package.json 오타 수정

src/components/createRetro/DescriptionBox.tsx, src/components/createRetro/PersonalRetroDescription.tsx, src/components/createRetro/TeamRetroDescription.tsx, src/styles/createRetro/CreateButtonBox.style.ts, src/styles/createRetro/Description.style.ts, src/styles/createRetro/DescriptionBox.style.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX17DoJ3Xj7eOSEi9RMEePT9wL9j6CtIrE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=WpXy4-n)
CreateRetro UI 수정 
<br><br>
피그마에서 수정된 팀 회고 소개, 개인 회고 소개 설명 수정
<br><br>
<br><br>
- Close #86 
<br><br>
=> [FE][Feature] CreateRetro UI 수정 

src/components/createRetro/modal/CreateModal.tsx, src/components/createRetro/modal/DescriptionInput.tsx, src/styles/createRetro/modal/CreateModal.style.ts
CreateRetro 설명 작성창 퍼블리싱
<br><br>
Figma에서 PM 팀이 추가한 회고 설명 작성 입력창 퍼블리싱 완료
<br><br>
<br><br>
- Close #98 
<br><br>
=> [FE][Feature] CreateRetro 설명 작성창 추가

src/App.tsx, src/components/survey/AgeInput.tsx, src/components/survey/CityRadio.tsx, src/components/survey/GenderRadio.tsx, src/components/survey/JobSelect.tsx, src/components/survey/PathRadio.tsx, src/components/survey/PurposeCheckbox.tsx, src/index.css, src/pages/SurveyPage.tsx, src/styles/survey/AgeInput.style.ts, src/styles/survey/CityRadio.style.ts, src/styles/survey/GenderRadio.style.ts, src/styles/survey/JobSelect.style.ts, src/styles/survey/PathRadio.style.ts, src/styles/survey/PurposeCheckbox.style.ts, src/styles/survey/SurveyPage.style.ts
SurveyPage 퍼블리싱 완료
<br><br>
설문조사에 해당 되는 1번~6번 문항 및 제출 버튼 퍼블리싱 완료
<br><br>
<br><br>
- Close #100 
<br><br>
=> [FE][Feature] SurveyPage 퍼블리싱

package.json, src/App.tsx, src/components/createRetro/modal/CreateModal.tsx, src/components/inviteTeam/InviteTeamModal.tsx, src/styles/inviteTeam/InviteTeamModal.style.ts, yarn.lock
InviteTeam Modal 퍼블리싱 완료
<br><br>
QR코드, 링크 복사, 링크 만료 시간 퍼블리싱 완료
<br><br>
qrcode.react 라는 라이브러리 설치했음
모달에서 모달로 넘어가는 게 구현하기 힘들어서 router 설정으로 처리함...
<br><br>
- Close #83 
<br><br>
=> [FE][Feature] Invite Team Modal 퍼블리싱

src/styles/Main/Contact.styles.ts
Main-Contact 화면 디자인 수정
Contact 화면 동그라미 z-index 수정
<br/>
- 이슈번호 [issue #122](https://github.com/donga-it-club/past-forward-frontend/issues/114)
<br><br>
=> :lipstick: Design: Main-Contact 화면 디자인 수정

src/App.tsx, src/components/writeRetro/layout/Manage.tsx, src/components/writeRetro/layout/Setting.tsx, src/pages/WriteRetroReviseTeamPage.tsx, src/styles/writeRetroStyles/ReviseLayout.style.ts
app.tsx 경로 재설정 및 WriteRetroRevise 페이지 기능 추가
<br><br>
<br><br>
<br><br>
- 이슈번호 [issue #118](https://github.com/donga-it-club/past-forward-frontend/issues/118)
<br><br>
=> :sparkles: Feat : app.tsx 경로 재설정 및 WriteRetroRevise 페이지 기능 추가

src/components/layout/parts/MenuBar.tsx
Main 페이지 내비 태그 연결
<br><br>
<br><br>
- 이슈번호 [issue #132 ](https://github.com/donga-it-club/past-forward-frontend/issues/132)
<br><br>
=> :sparkles: Feat: Main 페이지 내비 태그 연결

src/App.tsx
RetroList 페이지 경로 추가
App.tsx 파일 경로 추가
<br><br>
<br><br>
=> :sparkles: Feat: RetroList 페이지 경로 추가

src/App.tsx, src/components/home/MainDesign.tsx, src/components/layout/parts/MainNavBar.tsx, src/components/layout/parts/MenuBar.tsx, src/components/layout/parts/PageSideBar.tsx, src/components/layout/parts/ProfileNavBar.tsx, src/components/my/EmailBox.tsx, src/components/user/UserEmail.tsx, src/styles/layout/layout.style.ts
레이아웃(각종 네브바)에 유저 관련된 api 연결
<br><br>
MainNavBar, ProfileNavBar, PageSideBar 수정
각종 create와 관련된 버튼들 /create로 바로 가게 수정
유저 이메일과 관련된 부분 재사용가능한 컴포넌트화
<br><br>
<br><br>
- 이슈번호 [issue #141](https://github.com/donga-it-club/past-forward-frontend/issues/141)
<br><br>
=> [FE][Feature] 레이아웃에 유저 관련된 api 연결

src/api/@types/@asConst.ts, src/api/@types/Retrospectives.ts, src/api/__mock__/retrospective.ts, src/api/axiosConfig.tsx, src/api/retrospectivesApi.tsx, src/components/createRetro/modal/CreateModal.tsx, src/components/createRetro/modal/DescriptionInput.tsx, src/components/createRetro/modal/ImageUpload.tsx, src/components/createRetro/modal/StartDateCalender.tsx, src/components/createRetro/modal/TemplateSelect.tsx, src/components/createRetro/modal/TitleInput.tsx, webpack.config.js
CreateRetro API 연결을 위한 사전 작업 완료
<br><br>
webpack proxy 설정, axiosConfig 추가, retrospectives api 추가, 타입 수정
<br><br>
<br><br>
- 이슈번호 [issue #134 ](https://github.com/donga-it-club/past-forward-frontend/issues/134)
<br><br>
=> [FE][Feature] CreateRetro API 연결

.eslintcache, src/api/@types/User.ts, src/api/axiosConfig.tsx, src/api/imageApi/getUser.tsx, src/api/imageApi/postImageToS3.tsx, src/api/imageApi/putUserThumbnail.tsx, src/pages/MyPage.tsx
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19pDSEzRpzMP4thUvqQEwdJbwGU5y6kk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=nEfIyA-)
유저 정보 조회, 사진 등록 api 연결 완료
<br><br>
user GET 요청 작업 완료
user thumbnail PUT 요청 작업 완료
<br><br>
추후 userId=1이 아닌 헤더에 토큰 전송하는 형식으로 변경 예정
<br><br>
- 이슈번호 [issue #155](https://github.com/donga-it-club/past-forward-frontend/issues/155)
<br><br>
=> [FE][Feature] User 관련 api 연결

src/App.tsx, src/components/inviteTeam/InviteTeamModal.tsx, src/components/writeRetro/revise/ManageTeamMembers.tsx
revise 에서 팀원 초대 모달 구현 완료
<br><br>
팀원 초대 버튼 눌렀을 때 모달 on, x 나 그 외 영역 눌렀을 때 off 가능하게 구현 완료
api 응답 값 렌더링 완료
<br><br>
응답 값으로 주어지는 링크랑 QR이미지가 작동 안됨
<br><br>
- 이슈번호 [issue #153](https://github.com/donga-it-club/past-forward-frontend/issues/153)
<br><br>
=> [FE][Feature] 팀원 초대 api 연결

src/App.tsx, src/api/services/Section.ts, src/components/layout/parts/PageSideBar.tsx, src/components/writeRetro/task/TeamTask.tsx, src/mocks/handlers.ts, src/styles/layout/layout.style.ts
<br><br>
- section 페이지 api 수정
- 사이드바 디자인 수정
-  revise 페이지 - 팀원 조회 api 수정
<br><br>
<br><br>
- 이슈번호 [issue #164](https://github.com/donga-it-club/past-forward-frontend/issues/164)
<br><br>
=> #164 [Fix] section 페이지 api 수정 (사이드바 디자인 수정 및 revise 페이지 - 팀원 조회 api 수정)

src/api/@types/Survey.ts, src/api/axiosConfig.tsx, src/api/survey/postSurvey.tsx, src/components/survey/AgeInput.tsx, src/components/survey/CityRadio.tsx, src/components/survey/GenderRadio.tsx, src/components/survey/JobSelect.tsx, src/components/survey/PathRadio.tsx, src/components/survey/PurposeCheckbox.tsx, src/pages/SurveyPage.tsx, yarn.lock
Survey API 연결
<br><br>
Survey API 연결
<br><br>
<br><br>
- 이슈번호 [issue #152](https://github.com/donga-it-club/past-forward-frontend/issues/152)
<br><br>
=> :sparkles: Feat : Survey API 연결

src/api/@types/Thumbnail.ts, src/api/imageApi/postImageToS3.tsx, src/components/RetroList/ContentsList.tsx, src/components/createRetro/modal/CreateModal.tsx, src/components/createRetro/modal/ImageUpload.tsx, src/components/writeRetro/revise/ReviseSetting.tsx, src/styles/RetroList/ContentsList.styles.ts
사진 조회 수정 완료
<br><br>
회고 생성 시 문제 있었던 사진 관련해서 수정 완료
<br><br>
민석님께서 코드 수정해주신 부분 반영했고, 타입 관련 부분 수정했습니다.
icon에서 오류가 있어 해당 부분 수정 완료했습니다.
<br><br>
- 이슈번호 [issue #171](https://github.com/donga-it-club/past-forward-frontend/issues/171)
<br><br>
=> [FE][Fix] 사진 S3 업로드 관련 수정 #171

src/api/@types/Retrospectives.ts, src/api/@types/User.ts, src/api/axiosConfig.tsx, src/components/RetroList/ContentsList.tsx, src/components/createRetro/modal/ImageUpload.tsx, src/pages/MyPage.tsx, src/pages/RetroListPage.tsx
날짜 한국 시간으로 수정 완료
<br><br>
회고 생성일 날짜 형식 수정
생성자 닉네임 렌더링 완료
<br><br>
<br><br>
- 이슈번호 [issue #192](https://github.com/donga-it-club/past-forward-frontend/issues/192)
<br><br>
=> [FE][Fix] retroList 날짜 렌더링 수정

src/api/@types/Retrospectives.ts, src/components/layout/parts/PageSideBar.tsx, src/components/writeRetro/revise/RetroImageUploader.tsx, src/components/writeRetro/revise/ReviseSetting.tsx, src/pages/RevisePage.tsx, src/pages/SectionPage.tsx
<br><br>
- api connection - 주로 revise 페이지
- 사이드바 디자인 수정 (retrolist 버튼 삽입)
<br><br>
<br><br>
<br><br>
=> [Fix]api connection - 주로 revise 페이지

src/api/axiosConfig.tsx, webpack.config.js
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19zeICdK2ICZ1xDIMoHisl0vwEksIoyFM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=tjfsTcq)
baseURL 끝에 / 제거
<br><br>
axiosInstance, webpackConfig 수정
<br><br>
<br><br>
- 이슈번호 [issue #205](https://github.com/donga-it-club/past-forward-frontend/issues/205)
<br><br>
=> [FE][Fix] 자동으로 url에 '/' 추가되는 이슈 수정 

src/api/axiosConfig.tsx, webpack.config.js
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19W9L3qys5AhDdyMkU1XthY4820jMZAuc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=vPNfWP6)
baseURL 슬래시 제거
<br><br>
<br><br>
<br><br>
<br><br>
=> [FE][Release] 240421 url 문제 해결 중

src/App.tsx
<br><br>
<br><br>
<br><br>
<br><br>
=> fix: navigate 오류 수정

src/components/RetroList/BookmarkButton.tsx, src/components/RetroList/ContentsFilter.tsx, src/components/RetroList/ContentsList.tsx, src/components/RetroList/OrderButton.tsx, src/components/RetroList/ProgressButton.tsx, src/components/RetroList/Search.tsx, src/components/RetroList/ViewButton.tsx, src/components/createRetro/modal/CreateModal.tsx, src/components/createRetro/modal/ImageUpload.tsx, src/components/createRetro/modal/StartDateCalender.tsx, src/components/createRetro/modal/TemplateSelect.tsx, src/components/createRetro/modal/TitleInput.tsx, src/components/home/MainDesign.tsx, src/components/inviteTeam/InviteTeamModal.tsx, src/components/layout/parts/MainNavBar.tsx, src/components/layout/parts/MenuBar.tsx, src/components/my/NicknameBox.tsx, src/components/my/PasswordBox.tsx, src/components/survey/AgeInput.tsx, src/components/writeRetro/layout/AddTask.tsx, src/components/writeRetro/layout/Title.tsx, src/components/writeRetro/task/TeamTask.tsx, src/pages/SurveyPage.tsx
버튼명 id 추가하기
<br><br>
<br><br>
<br><br>
- 이슈번호 [issue #126](https://github.com/donga-it-club/past-forward-frontend/issues/126)
<br><br>
=> :sparkles: Feat : 버튼명 id 추가하기

src/api/@types/User.ts, src/api/axiosConfig.tsx, src/api/imageApi/putUser.tsx, src/components/my/NicknameBox.tsx, src/styles/my/myPage.style.ts
닉네임 수정할 수 있는 백엔드 api 추가 완료
<br><br>
put으로 닉네임만 수정할 수 있게끔 추가 함
<br><br>
<br><br>
- 이슈번호 [issue #212](https://github.com/donga-it-club/past-forward-frontend/issues/212)
<br><br>
=> [FE][Fix] 닉네임 변경 api 추가

src/pages/RetroListPage.tsx, src/pages/SurveyPage.tsx
RetroList 필터 로직 및 path 기본값 설정
<br><br>
RetroList 필터 로직 및 path 기본값 설정
<br><br>
<br><br>
- 이슈번호 [issue #169](https://github.com/donga-it-club/past-forward-frontend/issues/169)
<br><br>
=> :sparkles: Feat : RetroList 필터 로직 및 path 기본값 설정

src/api/@types/Thumbnail.ts, src/api/@types/User.ts, src/components/layout/parts/MainNavBar.tsx, src/components/layout/parts/PageSideBar.tsx, src/components/layout/parts/ProfileNavBar.tsx, src/components/my/component/ImageUploader.tsx, src/components/user/UserProfileImage.tsx, src/pages/MyPage.tsx, src/styles/my/myPage.style.ts
유저 사진 업로드, 사진 수정 가능하게 구현 완료
<br><br>
myPage에서 사진 등록 및 수정 가능하게 완료
각종 navbar에서 프로필 사진 불러올 수 있는 UserProfileImage 컴포넌트 구현 완료
<br><br>
저장 전 수정하려는 이미지는 제거가 되지만 기존 이미지는 제거되지 않음
<br><br>
- 이슈번호 [issue #185](https://github.com/donga-it-club/past-forward-frontend/issues/185)
<br><br>
=> [FE][Fix] 유저 프로필 사진 관련 수정

src/api/@types/Section.ts, src/api/__mock__/section.ts, src/api/services/Section.ts, src/components/inviteTeam/InviteTeamModal.tsx, src/components/layout/parts/PageSideBar.tsx, src/components/writeRetro/revise/ManageTeamMembers.tsx, src/components/writeRetro/revise/ReviseSetting.tsx, src/components/writeRetro/task/TeamTask.tsx, src/components/writeRetro/task/taskMessage/TeamTaskMessage.tsx, src/pages/SectionPage.tsx, src/pages/SurveyPage.tsx, src/styles/writeRetroStyles/Layout.style.ts
<br><br>
<br><br>
<br><br>
- 이슈번호 [issue #226](https://github.com/donga-it-club/past-forward-frontend/issues/226)
<br><br>
=> 🐛fix: section 프로필 이미지 코드 작성

src/pages/SurveyPage.tsx
설문조사 제출 navigate 수정
<br><br>
설문조사 제출 navigate 수정
<br><br>
<br><br>
- 이슈번호 [issue #215](https://github.com/donga-it-club/past-forward-frontend/issues/215)
<br><br>
=> :bug: Fix : 설문조사 제출 navigate 수정

src/components/user/UserProfileImage.tsx, src/pages/SurveyPage.tsx
<br><br>
<br><br>
<br><br>
- 이슈번호 [issue #203](https://github.com/donga-it-club/past-forward-frontend/issues/203)
<br><br>
=> [FE][Release] 240425 배포 테스트 전 빌드

src/components/survey/PurposeCheckbox.tsx
Reverts donga-it-club/past-forward-frontend#242
=> Revert "✨ Feat : Survey 질문 수정"

src/api/@types/Retrospectives.ts, src/api/@types/TeamController.tsx, src/api/services/Retrospectives.ts, src/components/createRetro/CreateButtonBox.tsx, src/components/inviteTeam/InviteTeamModal.tsx, src/components/writeRetro/revise/ManageTeamMembers.tsx, src/components/writeRetro/revise/ReviseSetting.tsx, src/pages/RevisePage.tsx
<br><br>
- 팀 멤버 프로필 이미지 렌더링
- create 버튼 클래스네임 지정
<br><br>
<br><br>
<br><br>
=> [Fix] team member profile image

src/components/survey/CityRadio.tsx, src/components/survey/GenderRadio.tsx, src/components/survey/PathRadio.tsx, src/components/survey/PurposeCheckbox.tsx
설문조사 질문 구분 Id 값 입력
<br><br>
설문조사 질문 구분 Id 값 입력
<br><br>
<br><br>
- 이슈번호 [issue #249](https://github.com/donga-it-club/past-forward-frontend/issues/249)
<br><br>
=> :sparkles: Feat: 설문조사 질문 구분 Id 값 입력

src/components/writeRetro/revise/ManageTeamMembers.tsx, src/components/writeRetro/task/TeamTask.tsx, src/components/writeRetro/task/taskMessage/TeamTaskMessage.tsx, src/pages/RevisePage.tsx
<br><br>
<br><br>
<br><br>
<br><br>
=> 🐛fix: 팀 멤버 이미지 렌더링 문제 해결 및 section 페이지 새로고침 이슈 해결

src/components/writeRetro/ActionItems/ActionItemTask.tsx, src/components/writeRetro/task/TeamTask.tsx
Action Items 담당자 이름 hover 안해도 뜨도록 설정
<br><br>
<br><br>
- 이슈번호 [issue #240 ](https://github.com/donga-it-club/past-forward-frontend/issues/240)
<br><br>
=> [FE][Fix] Action Items 담당자 이름 표시 수정

src/api/@types/Section.ts, src/api/services/Section.ts, src/components/inviteTeam/InviteTeamModal.tsx, src/components/writeRetro/layout/Title.tsx, src/components/writeRetro/revise/ManageTeamMembers.tsx, src/pages/RevisePage.tsx, src/pages/SectionPage.tsx
<br><br>
-  팀 멤버 삭제 렌더링 이슈 해결
<br><br>
<br><br>
<br><br>
=> 🐛fix: 팀 멤버 삭제 렌더링 이슈 해결

package.json, src/components/home/MainDesign.tsx, src/components/layout/parts/MainNavBar.tsx, src/delcaration.d.ts, src/pages/HomePage.tsx, src/styles/Main/About.styles.ts, src/styles/Main/Contact.styles.ts, src/styles/Main/Template1.styles.ts, src/styles/Main/Template2.styles.ts, src/styles/Main/Template3.styles.ts, yarn.lock
메인 페이지 react-fullpage 라이브러리 제거
<br><br>
<br><br>
- 이슈번호 [issue #265 ](https://github.com/donga-it-club/past-forward-frontend/issues/265 )
<br><br>
=> [FE][Fix] 메인 페이지 react-fullpage 라이브러리 제거

src/components/RetroList/ContentsList.tsx, src/styles/RetroList/ContentsList.styles.ts, src/styles/RetroList/Search.style.ts
RetroList 디자인 수정
- 검색창 삭제 버튼 위치 조정
- 리스트뷰 디자인 수정
<br><br>
- 이슈번호 [issue #274 ](https://github.com/donga-it-club/past-forward-frontend/issues/274 )
<br><br>
=> [FE][Design] RetroList 디자인 수정

src/components/RetroList/ContentsList.tsx, src/components/RetroList/Modal.tsx, src/styles/RetroList/ContentsList.styles.ts
RetroList 리더 관련 내용 수정
- 리더 본인 버튼 표시
- 회고 수정 모달 창 리더 권한 부여
- 리더 닉네임 말줄임 설정
<br><br>
- 이슈번호 [issue #267 ](https://github.com/donga-it-club/past-forward-frontend/issues/267 )
<br><br>
=> [FE][Feature] RetroList 리더 관련 내용 추가 및 수정

src/components/writeRetro/revise/BackButton.tsx, src/pages/RevisePage.tsx, src/styles/writeRetroStyles/BackButton.styles.ts
WriteRetroRevise 뒤로가기 버튼
<br><br>
<br><br>
- 이슈번호 [issue #276 ](https://github.com/donga-it-club/past-forward-frontend/issues/276 )
<br><br>
=> [FE][Feature] WriteRetroRevise 뒤로가기 버튼

src/components/createRetro/DescriptionBox.tsx, src/components/createRetro/PersonalRetroDescription.tsx, src/components/createRetro/TeamRetroDescription.tsx, src/components/createRetro/modal/CreateModal.tsx, src/components/writeRetro/task/TeamTask.tsx, src/components/writeRetro/task/taskMessage/TeamTaskMessage.tsx, src/styles/createRetro/Description.style.ts, src/styles/createRetro/DescriptionBox.style.ts
<br><br>
<br><br>
<br><br>
<br><br>
=> 💄Design: create 모달, create 페이지 디자인 수정

src/components/writeRetro/explainModal/explainRetro.tsx, src/pages/SectionPage.tsx, src/styles/writeRetroStyles/Explain.style.ts
회고 설명 모달 추가
<br><br>
- KPT 설명 모달 만들기
- Kudos 설명 모달 만들기
- 회고 설명 버튼 만들기
- 회고에 따라 설명 모달 연결하기
<br><br>
<br><br>
- 이슈번호 [issue #271](https://github.com/donga-it-club/past-forward-frontend/issues/271)
<br><br>
=> :sparkles: Feat: 회고 설명 모달 추가

src/components/layout/parts/PageSideBar.tsx, src/styles/layout/layout.style.ts
사이드바 그룹화 기능 버튼 추가
<br><br>
<br><br>
- 이슈번호 [issue #290 ](https://github.com/donga-it-club/past-forward-frontend/issues/290)
<br><br>
=> [FE][Feature] 사이드바 그룹화 기능 버튼 추가

src/components/RetroList/ContentsList.tsx, src/components/layout/parts/PageSideBar.tsx, src/pages/RetroListPage.tsx, src/styles/layout/layout.style.ts
RetroList 무한 로딩 버그 해결
사이드바 그룹화 기능 버튼 추가
<br><br>
<br><br>
- 이슈번호 [issue #286](https://github.com/donga-it-club/past-forward-frontend/issues/286)
- 이슈번호 [issue #290 ](https://github.com/donga-it-club/past-forward-frontend/issues/290)
<br><br>
=> [FE][Fix] RetroList 무한 로딩 버그 해결 

src/components/RetroList/ContentsList.tsx, src/pages/RetroListPage.tsx, src/styles/RetroList/ContentsFilter.style.ts, src/styles/RetroList/ContentsList.styles.ts, src/styles/RetroList/RetroListPage.style.ts, src/styles/RetroList/Search.style.ts, src/styles/RetroList/ViewButton.style.ts
RetroList 페이지 반응형 디자인 제작
<br><br>
<br><br>
<br><br>
- 이슈번호 [issue #288 ](https://github.com/donga-it-club/past-forward-frontend/issues/288)
<br><br>
=> [FE][Design] RetroList 페이지 반응형 디자인 제작

src/components/Main/Contact.tsx, src/components/writeRetro/layout/RetroTitle.tsx, src/components/writeRetro/layout/Title.tsx, src/components/writeRetro/revise/BackButton.tsx, src/components/writeRetro/revise/ManageTeamMembers.tsx, src/components/writeRetro/revise/RetroImageUploader.tsx, src/components/writeRetro/revise/ReviseSetting.tsx, src/pages/RevisePage.tsx, src/pages/SectionPage.tsx, src/styles/writeRetroStyles/BackButton.styles.ts, src/styles/writeRetroStyles/Explain.style.ts, src/styles/writeRetroStyles/Layout.style.ts, src/styles/writeRetroStyles/ReviseLayout.style.ts
Section 페이지 및 회고 수정 페이지 반응형 디자인으로 만들기
<br><br>
- Section 페이지 반응형 디자인으로 만들기
- 회고 수정 페이지 반응형 디자인으로 만들기
<br><br>
<br><br>
- 이슈번호 [issue #287](https://github.com/donga-it-club/past-forward-frontend/issues/287)
<br><br>
=> :lipstick: Design : Section 페이지 및 회고 수정 페이지 반응형 디자인으로 만들기

src/components/Main/Contact.tsx, src/components/survey/PurposeCheckbox.tsx, src/components/writeRetro/explainModal/explainRetro.tsx, src/components/writeRetro/layout/Title.tsx, src/pages/SectionPage.tsx, src/pages/SurveyPage.tsx, src/styles/Main/Contact.styles.ts, src/styles/survey/PurposeCheckbox.style.ts, src/styles/survey/SurveyPage.style.ts, src/styles/writeRetroStyles/Explain.style.ts, src/styles/writeRetroStyles/Layout.style.ts
Contact 및 Survey 페이지 반응형 디자인으로 만들기
<br><br>
- Contact 반응형 디자인으로 만들기
- 설문조사 페이지 반응형 디자인으로 만들기
<br><br>
<br><br>
- 이슈번호 [issue #300](https://github.com/donga-it-club/past-forward-frontend/issues/300)
<br><br>
=> :lipstick: Design: Contact 및 Survey 페이지 반응형 디자인으로 만들기

src/App.tsx, src/components/notice/NoticeBoard.tsx, src/components/notice/NoticeMenuBar.tsx, src/components/notice/NoticeShowFooter.tsx, src/components/notice/NoticeShowHeader.tsx, src/components/notice/NoticeWriteBox.tsx, src/components/writeRetro/layout/Title.tsx, src/pages/HomePage.tsx, src/pages/notice/NoticeShowPage.tsx, src/pages/notice/NoticeWritePage.tsx, src/styles/Main/Contact.styles.ts, src/styles/notice/noticeBoard.style.ts, src/styles/notice/noticeShow.style.ts, src/styles/notice/noticeWrite.style.ts, src/styles/writeRetroStyles/Layout.style.ts
공지사항 게시판 퍼블리싱
<br><br>
공지사항 게시판 퍼블리싱
<br><br>
<br><br>
- 이슈번호 [issue #302](https://github.com/donga-it-club/past-forward-frontend/issues/302)
<br><br>
=> :lipstic: Design: 공지사항 게시판 퍼블리싱

src/api/@types/@asConst.ts, src/api/@types/Notification.ts, src/api/services/Notification.ts, src/components/alarm/Alarm.tsx, src/components/inviteTeam/InviteTeamModal.tsx, src/components/layout/parts/PageSideBar.tsx, src/constant/notification.ts, src/styles/layout/layout.style.ts
<br><br>
<br><br>
<br><br>
<br><br>
=> [✨ Feat #308] 알림 기능 구현

src/api/@types/Groups.ts, src/api/retroGroupsApi/postGroup.tsx, src/components/projectRetro/CreateModal.tsx, src/components/projectRetro/DescriptionInput.tsx, src/components/projectRetro/GroupList.tsx, src/components/projectRetro/Modal.tsx, src/components/projectRetro/TitleInput.tsx, src/pages/ProjectRetroPage.tsx, src/styles/projectRetro/CreateModal.styles.ts, src/styles/projectRetro/Modal.styles.ts
ProjectRetro 그룹 생성하기 모달창 구현
<br><br>
<br><br>
- 이슈번호 [issue #306 ](https://github.com/donga-it-club/past-forward-frontend/issues/306)
<br><br>
=> [FE][Feature] ProjectRetro 그룹 생성하기 모달창 구현

src/api/@types/Groups.ts, src/api/retroGroupsApi/deleteGroup.tsx, src/api/retroGroupsApi/getGroup.tsx, src/components/createRetro/modal/CreateModal.tsx, src/components/createRetro/modal/ImageUpload.tsx, src/components/projectRetro/DeleteModal.tsx, src/components/projectRetro/DescriptionInput.tsx, src/components/projectRetro/GroupList.tsx, src/components/projectRetro/Modal.tsx, src/components/projectRetro/TitleInput.tsx, src/pages/ProjectRetroPage.tsx, src/styles/projectRetro/DeleteModal.styles.ts, src/styles/projectRetro/Modal.styles.ts
ProjectRetro 그룹 삭제 구현
- ProjectRetro 그룹 삭제 구현
- 개별 그룹 조회 api 연결(진행중)
<br><br>
- 이슈번호 [issue #317 ](https://github.com/donga-it-club/past-forward-frontend/issues/317)
<br><br>
=> [FE][Feature] ProjectRetro 그룹 삭제 구현

src/api/@types/Groups.ts, src/api/retroGroupsApi/putGroup.tsx, src/components/projectRetro/DeleteModal.tsx, src/components/projectRetro/DescriptionInput.tsx, src/components/projectRetro/GroupList.tsx, src/components/projectRetro/Modal.tsx, src/components/projectRetro/TitleInput.tsx, src/pages/ProjectRetroPage.tsx, src/styles/projectRetro/GroupList.styles.ts, src/styles/projectRetro/Modal.styles.ts, src/styles/projectRetro/ProjectRetroPage.styles.ts
ProjectRetro PUT api 연결
- ProjectRetro PUT api 연결
- 그룹 리스트 퍼블리싱
<br><br>
- 이슈번호 [issue #304 ](https://github.com/donga-it-club/past-forward-frontend/issues/304)
- 이슈번호 [issue #307](https://github.com/donga-it-club/past-forward-frontend/issues/307)
<br><br>
=> [FE][Feature] ProjectRetro PUT api 연결

src/App.tsx, src/api/@types/Groups.ts, src/components/projectRetro/GroupBoardList.tsx, src/pages/GroupBoardPage.tsx, src/styles/projectRetro/GroupBoard.styles.ts, src/styles/projectRetro/GroupBoardList.styles.ts, src/styles/projectRetro/GroupList.styles.ts
ProjectRetro 개별 그룹 화면 제작
<br><br>
<br><br>
- 이슈번호 [issue #319](https://github.com/donga-it-club/past-forward-frontend/issues/319)
<br><br>
=> [FE][Feature] ProjectRetro 개별 그룹 페이지 제작

src/components/RetroList/Search.tsx
RetroList 검색창 문구 수정
Search Tasks -> Search Retrospect
<br><br>
- 이슈번호 [issue #326 ](https://github.com/donga-it-club/past-forward-frontend/issues/326)
<br><br>
=> [FE][Design] RetroList 검색창 문구 수정

src/App.tsx, src/api/@types/Groups.ts, src/components/RetroList/Search.tsx, src/components/layout/parts/OtherNav.tsx, src/components/layout/parts/PageSideBar.tsx, src/components/projectRetro/GroupBoardList.tsx, src/components/projectRetro/GroupList.tsx, src/hooks/useSingleAndDoubleClick.tsx, src/pages/GroupBoardPage.tsx, src/styles/projectRetro/GroupBoard.styles.ts, src/styles/projectRetro/GroupBoardList.styles.ts, src/styles/projectRetro/GroupList.styles.ts
<br><br>
<br><br>
<br><br>
<br><br>
=> [FE][Release] 240723 중간 빌드

src/api/@types/NoticeBoard.ts, src/api/@types/Survey.ts, src/api/@types/User.ts, src/api/@types/Users.ts, src/api/services/NoticeBoard.ts, src/api/services/User.ts, src/components/notice/NoticeBoard.tsx, src/components/notice/NoticeBoardContents.tsx, src/components/notice/NoticeMenuBar.tsx, src/components/notice/NoticePagination.tsx, src/components/notice/NoticeShowFooter.tsx, src/components/notice/NoticeShowHeader.tsx, src/components/notice/NoticeShowMain.tsx, src/components/notice/NoticeWriteBox.tsx, src/components/survey/EmailConsents.tsx, src/pages/HomePage.tsx, src/pages/SurveyPage.tsx, src/pages/notice/NoticeShowPage.tsx, src/pages/notice/NoticeWritePage.tsx, src/styles/notice/noticeBoard.style.ts, src/styles/notice/noticeShow.style.ts, src/styles/notice/noticeWrite.style.ts, src/styles/survey/EmailConsents.style.ts
게시판 api 연결
<br><br>
- 게시글 작성 api 연결
- 게시글 수정 api 연결
- 게시글 삭제 api 연결
<br><br>
<br><br>
- 이슈번호 [issue #310](https://github.com/donga-it-club/past-forward-frontend/issues/310)
<br><br>
=> ✨ Feat: 게시판 api 연결

src/api/@types/Users.ts, src/components/Main/Contact.tsx, src/components/notice/NoticeBoard.tsx, src/pages/SectionPage.tsx, src/pages/notice/NoticeWritePage.tsx, src/styles/writeRetroStyles/Layout.style.ts
디자인 수정사항 적용 및 Section Page 반응형 수정
<br><br>
- Contact 이메일 입력란 문구 수정
- Section 페이지 Section 정렬 수정
- 회고 카드 생성 시 최근 카드가 맨 위쪽으로 오도록 수정
<br><br>
<br><br>
- 이슈번호 [issue #333](https://github.com/donga-it-club/past-forward-frontend/issues/333)
<br><br>
=> :lipstick: Design: 디자인 수정사항 적용 및 Section Page 반응형 수정

src/api/@types/Groups.ts, src/api/retroGroupsApi/putBoard.tsx, src/api/retrospectivesApi/getRetrospective.tsx, src/components/projectRetro/ManageModal.tsx, src/pages/GroupBoardPage.tsx, src/styles/projectRetro/ManageModal.styles.ts
ProjectRetro 그룹 회고 관리 화면
<br><br>
<br><br>
- 이슈번호 [issue #320 ](https://github.com/donga-it-club/past-forward-frontend/issues/320 )
<br><br>
=> [FE][Feature] ProjectRetro 그룹 회고 관리 화면

src/components/RetroList/ContentsList.tsx, src/components/projectRetro/GroupBoardList.tsx, src/styles/projectRetro/ManageModal.styles.ts
ProjectRetro 기능 추가 및 수정
- 단일 그룹 페이지 - navigate 연결
- 로딩 화면 구현
- 콘솔 삭제
<br><br>
- 이슈번호 [issue #337 ](https://github.com/donga-it-club/past-forward-frontend/issues/337)
<br><br>
=> [FE][Feature] ProjectRetro 기능 추가 및 수정

src/api/@types/NoticeBoard.ts, src/components/notice/NoticeBoard.tsx, src/components/notice/NoticeBoardContents.tsx, src/components/notice/NoticeMenuBar.tsx, src/components/notice/NoticePagination.tsx, src/components/notice/NoticeShowFooter.tsx, src/components/notice/NoticeShowHeader.tsx, src/pages/SectionPage.tsx, src/pages/notice/NoticeShowPage.tsx, src/styles/writeRetroStyles/Layout.style.ts
Section Page 반응형 수정 및 개별 게시물 네비게이션 기능 추가
<br><br>
- Section Page 반응형 수정
- 개별 게시물 네비게이션 기능 추가
<br><br>
<br><br>
- 이슈번호 [issue #332](https://github.com/donga-it-club/past-forward-frontend/issues/332)
<br><br>
=> :sparkles: Feat: Section Page 반응형 수정 및 개별 게시물 네비게이션 기능 추가

src/components/notice/FakeNotice/FakeNoticeShowMain.tsx
임시 게시물 오타 수정
<br><br>
임시 게시물 오타 수정
<br><br>
<br><br>
- 이슈번호 [issue #347](https://github.com/donga-it-club/past-forward-frontend/issues/347)
<br><br>
=> :sparkles: Feat: 임시 게시물 오타 수정

src/pages/ProjectRetroPage.tsx, src/styles/projectRetro/DeleteModal.styles.ts, src/styles/projectRetro/DescriptionModal.styles.ts, src/styles/projectRetro/GroupBoard.styles.ts, src/styles/projectRetro/GroupBoardList.styles.ts, src/styles/projectRetro/GroupList.styles.ts, src/styles/projectRetro/ManageModal.styles.ts, src/styles/projectRetro/Modal.styles.ts, src/styles/projectRetro/ProjectRetroPage.styles.ts
ProjectRetro 반응형 디자인 제작
<br><br>
<br><br>
- 이슈번호 [issue #349 ](https://github.com/donga-it-club/past-forward-frontend/issues/349)
<br><br>
=> [FE][Design] ProjectRetro 반응형 디자인 제작

src/components/RetroList/ContentsList.tsx, src/components/projectRetro/GroupBoardList.tsx, src/components/projectRetro/ManageModal.tsx, src/pages/GroupBoardPage.tsx, src/styles/RetroList/ContentsList.styles.ts, src/styles/projectRetro/DeleteModal.styles.ts, src/styles/projectRetro/GroupBoard.styles.ts, src/styles/projectRetro/ManageModal.styles.ts
ProjectRetro QA 오류 사항 수정
- 프로젝트 설명 텍스트 추가
- p-16
- p-17
- p-19
[QA 테스트지](https://docs.google.com/spreadsheets/d/1xiamQcdWjbo5vV3p_FPaPgmLViKWe0pbJLOOMmgLLd8/edit?gid=0#gid=0)
- 이슈번호 [issue #342 ](https://github.com/donga-it-club/past-forward-frontend/issues/342)
<br><br>
=> [FE][Fix] ProjectRetro QA 테스트 오류 사항 수정

src/api/@types/Section.ts, src/api/@types/TeamController.tsx, src/api/teamControllerApi/putKudosTarget.tsx, src/components/projectRetro/ManageModal.tsx, src/components/writeRetro/KudosTarget/KudosTargetButton.tsx, src/components/writeRetro/KudosTarget/Members.tsx, src/components/writeRetro/task/TeamTask.tsx, src/styles/projectRetro/ManageModal.styles.ts, src/styles/writeRetroStyles/Layout.style.ts
240730 배포 전 빌드
<br><br>
<br><br>
<br><br>
=> [FE][Release] 240730 배포 전 빌드
